### PR TITLE
Add Telegram backup

### PR DESCRIPTION
**Pull request by MAPKOBKA135**
Add Periodical Telegram backup

### CODE REVIEW

**Comment by dragonx943** [comment]
> Add Telegram backup

backup what ???

**Comment by MAPKOBKA135** [comment]
> > Add Telegram backup
> 
> backup what ???

Periodical backup to telegram

**Comment by dragonx943** [comment]
> > > Add Telegram backup
> > 
> > 
> > backup what ???
> 
> Periodical backup to telegram

but backup what ???

**Comment by MAPKOBKA135** [comment]
> > > > Add Telegram backup
> > > 
> > > 
> > > backup what ???
> > 
> > 
> > Periodical backup to telegram
> 
> but backup what ???

settings > data and privacy > periodic backups
This is done so that you don't have to worry about data loss after factory reset

**Comment by MAPKOBKA135** [comment]
> > > > > Add Telegram backup
> > > > 
> > > > 
> > > > backup what ???
> > > 
> > > 
> > > Periodical backup to telegram
> > 
> > 
> > but backup what ???
> 
> settings > data and privacy > periodic backups This is done so that you don't have to worry about data loss after factory reset At the moment when a periodic backup is created, it is sent to telegram via a bot in private messages

**Comment by nichind** [comment]
merge ASAP, this would be actually useful

**Comment by dragonx943** [comment]
> merge ASAP, this would be actually useful 

nope :p

**Pull request merged**
