### PR TITLE
Simplify history cleanup using Instant.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) to allow `java.time` to be used on API levels < 26.
* Use [`Instant`](https://developer.android.com/reference/java/time/Instant) and its related classes for the timestamp calculation.
* Cleanup unused extension methods.

### CODE REVIEW

**Comment by Koitharu** [comment]
Not sure if it is worth adding desugaring just to use Instant in the only one place.

**Comment by Isira-Seneviratne** [comment]
I thought I would start with a relatively small change, since this is my first contribution to this app.

**Comment by Koitharu** [comment]
I`m not sure we will merge it since I have some concerns about desugaring and how it will affect the build time and apk size

**Comment by Isira-Seneviratne** [comment]
The app size is increased by 170 KB, and there doesn't seem to be much impact on the build time.

**Pull request closed without merging**
