### PR TITLE
Hide toolbar when scrolling up

### PR DESCRIPTION
**Pull request by VietAnh14**
Fix tab layout overlap with status bar

https://github.com/user-attachments/assets/3109d481-59d6-460c-a1a5-1795f11076a3

### CODE REVIEW

**Comment by Koitharu** [comment]
It looks really cool for favorites but for other screens with lists it breaks the edge-to-edge concept. I wonder if we can use it only on the favorites screen?

**Comment by VietAnh14** [comment]
We would need to handle app bar insets for each screen then, I'll try to see if I can do anything

**Comment by wolfkin** [comment]
nice this seems to solve a UI thing that bugged me. Where text would get stuck behind the status bar


https://github.com/user-attachments/assets/4f2f9b75-ae30-4ade-a668-39fac33eb804

**Comment by VietAnh14** [comment]
Finally got time to work on this, I've apply it to favorite screen only

https://github.com/user-attachments/assets/de4cb454-7eeb-4f1f-b104-835b7a4f91f4

**Pull request merged**
